[phases.setup]
nixPkgs = ["php", "nodejs", "composer", "coreutils", "mysql-client"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm install && npm run build",
  "php artisan key:generate --force",
  "php artisan migrate --force",
  "php artisan config:clear",
  "php artisan cache:clear",
  "php artisan route:cache",
  "php artisan view:cache",
  "chmod -R 777 storage bootstrap/cache"
]

[phases.start]
cmds = ["php artisan serve --host=0.0.0.0 --port=${PORT}"]
